version: '3'
networks:
  openhim:

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.0
    networks:
      - openhim
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped

  himcore:
    container_name: core
    image: jabahum/himcore:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim-development"
      mongo_atnaUrl: "mongodb://mongo-db/openhim-development"
      NODE_ENV: "development"
    ports:
      - "8081:8081"
      - "5000:5000"
      - "5001:5001"
    networks:
      - openhim
    healthcheck:
     test: "curl -sSk https://himcore:8081/heartbeat || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3

  himconsole:
    container_name: console
    image: jabahum/himconsole:latest
    restart: unless-stopped
    networks:
      - openhim
    ports:
      - "9000:80"
    healthcheck:
     test: "curl -sS http://himconsole || exit 1"
     interval: 30s
     timeout: 30s
     retries: 3

volumes:
  mongo-data:
